const SPOT_IT_SYMBOL_GLYPHS: Readonly<Record<string, string>> = {
  sun: '☀️',
  moon: '🌙',
  star: '⭐',
  heart: '❤️',
  lightning: '⚡',
  snowflake: '❄️',
  fire: '🔥',
  'water-drop': '💧',
  tree: '🌳',
  flower: '🌸',
  leaf: '🍃',
  apple: '🍎',
  cherry: '🍒',
  lemon: '🍋',
  watermelon: '🍉',
  carrot: '🥕',
  mushroom: '🍄',
  ladybug: '🐞',
  butterfly: '🦋',
  bee: '🐝',
  fish: '🐟',
  turtle: '🐢',
  bird: '🐦',
  cat: '🐈',
  dog: '🐕',
  rabbit: '🐇',
  frog: '🐸',
  octopus: '🐙',
  whale: '🐋',
  crab: '🦀',
  anchor: '⚓',
  sailboat: '⛵',
  airplane: '✈️',
  car: '🚗',
  bicycle: '🚲',
  rocket: '🚀',
  house: '🏠',
  key: '🔑',
  crown: '👑',
  diamond: '💎',
  bell: '🔔',
  clock: '🕒',
  camera: '📷',
  'music-note': '🎵',
  umbrella: '☂️',
  glasses: '👓',
  scissors: '✂️',
  pencil: '✏️',
  book: '📕',
  lightbulb: '💡',
  magnet: '🧲',
  balloon: '🎈',
  gift: '🎁',
  'soccer-ball': '⚽',
  dice: '🎲',
  ghost: '👻',
  smile: '🙂',
}

export function getSpotItSymbolPresentation(symbolId: string) {
  return {
    glyph: SPOT_IT_SYMBOL_GLYPHS[symbolId] ?? '❓',
    label: symbolId
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' '),
  }
}
